# Generated by Django 4.2.6 on 2023-10-27 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticy',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False, verbose_name='Criticy ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False, verbose_name='Speciality ID')),
                ('name', models.CharField(max_length=50, verbose_name='Speciality Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_History',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False, verbose_name='Ticket History ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Ticket Update')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ticket Published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Ticket Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ticket Title'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ticket Updated'),
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False, verbose_name='Tech ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tech Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Tech Last_Name')),
                ('speciality', models.ManyToManyField(blank=True, null=True, to='core.speciality', verbose_name='Speciality Name')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='criticy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.criticy', verbose_name='Ticket Criticy'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket_history', verbose_name='Ticket History'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tech',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tech', verbose_name='Tech'),
        ),
    ]
